sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhisheksil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhisheksil/docker-react npm run test -- --coverage
